version: "3.9"

services:
  jupyterlab:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      # You can replace "./notebooks" with any folder you want to persist
      - ./notebooks:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=token
      # Optional: disable password entirely (redundant when using token)
      - JUPYTER_PASSWORD=
    command: start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}' --NotebookApp.password=''

volumes:
  jupyter_data:
